spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            scope: name,email
            client-secret: AuthKey_9236K65RMT.p8
            client-authentication-method: POST
            client-id: com.env.dosirak
            redirect-uri: https://dosirak.store:80/login/oauth2/code/apple
            client-name: Apple
            authorization-grant-type: authorization_code
          google:
            authorization-grant-type: authorization_code
            client-id: 555600757543-eof6pket21gur557hp7dfvdvpksfagf2.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email,profile
          kakao:
            client-secret: ahPbJHsslw3q4gzNRjwRW8piLRsk67sQ
            authorization-grant-type: authorization_code
            client-id: 257ecc168d86f97dddf52f4d6f6928e2
            scope: profile_nickname,account_email,profile_image
            client-authentication-method: client_secret_post
            redirect_uri: http://dosirak.store:80/login/oauth2/code/kakao
            client-name: kakao
          naver:
            client-name: naver
            client-id: RofRaqjYRCQ7jBPmLPLc
            redirect-uri: http://dosirak.store:80/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-secret: hhF40YzMjn
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
          apple:
            token-uri: https://appleid.apple.com/auth/token
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
  cache:
    type: simple
  thymeleaf:
    check-template-location: 'false'
  application:
    name: dosirak-be
  datasource:
    password: ENC(SCFNVMgdRn7yYtqXwcszKTQSASRKfcMB)
    url: jdbc:mysql://dosirak-db.chu8ks2ces6a.ap-northeast-2.rds.amazonaws.com/dosirak
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(0RoDth/FNbUfXKKRzW/rWg==)
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jwt:
    access-token:
      expiration-time: '3600000'
    refresh-token:
      expiration-time: '604800000'
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
cloud:
  aws:
    stack:
      auto-: 'false'
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAUGCG7STB27LXLJYI
      secretKey: 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
    s3:
      bucketName: dosirakbucket
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
apple:
  kid: 9236K65RMT
  cid: com.env.dosirak
  path: static/apple/AuthKey_9236K65RMT.p8
  url: https://appleid.apple.com
  tid: AU24ZRJ649
server:
  port: '8080'
jasypt:
  encryptor:
    password: gpudosirak
openai:
  api-key: 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
