name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃 최신 코드를 가져옴
      - name: Checkout code
        uses: actions/checkout@v3

      # Asciidoctor 설치 (Ubuntu 환경에서)
      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install asciidoctor

      # AsciiDoc 파일을 HTML로 변환 (예시)
      - name: Build AsciiDoc to HTML
        run: |
          mkdir -p docs
          asciidoctor src/docs/asciidoc/index.adoc -o docs/index.html

      # 사용자 정보 설정
      - name: Set git user
        run: |
           git config --global user.name "femmefatalehaein"
           git config --global user.email "rmfls4359gmail.com"
           git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/DOSI-RAK/dosirak-be.git

      - name: Create gh-pages branch if not exists
        run: |
          echo "Checking if gh-pages branch exists"
          if ! git show-ref --quiet refs/heads/gh-pages; then
            echo "Creating gh-pages branch"
            git checkout --orphan gh-pages  # gh-pages 브랜치 생성
            git reset --hard                # 기존 파일 삭제
            git add docs/index.html         # HTML 파일만 추가
            git commit -m "Initial commit for GitHub Pages"
            echo "Pushing to GitHub Pages - 1"
            git push --force https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/DOSI-RAK/dosirak-be.git gh-pages
          else
            echo "Switching to existing gh-pages branch"
            git checkout gh-pages           # 기존 gh-pages 브랜치로 체크아웃
            git add docs/index.html         # HTML 파일만 추가
            git commit -m "Deploy to GitHub Pages"
            echo "Pushing changes to gh-pages - 2"
            git push --force https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/DOSI-RAK/dosirak-be.git gh-pages
          fi

      # GitHub Pages에 푸시 (이미 `gh-pages` 브랜치가 설정되어 있어야 함)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 기본 GitHub Actions 토큰 사용
          publish_dir: ./docs  # docs 폴더에 배포
