name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃 최신 코드를 가져옴
      - name: Checkout code
        uses: actions/checkout@v3

      # Asciidoctor 설치 (Ubuntu 환경에서)
      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install asciidoctor

      # AsciiDoc 파일을 HTML로 변환 (예시)
      - name: Build AsciiDoc to HTML
        run: |
          mkdir -p docs
          asciidoctor src/docs/asciidoc/index.adoc -o docs/index.html

      # orphan 브랜치 만들기
      - name: Create orphan branch for GitHub Pages
        run: |
          git checkout gh-pages  # gh-pages 브랜치 생성
          git add docs/index.html         # HTML 파일만 추가
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force

      # GitHub Pages에 푸시 (이미 `gh-pages` 브랜치가 설정되어 있어야 함)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs  # docs 폴더에 배포
