name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃 최신 코드를 가져옴
      - name: Checkout code
        uses: actions/checkout@v3

      # Asciidoctor 설치 (Ubuntu 환경에서)
      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install asciidoctor

      # AsciiDoc 파일을 HTML로 변환 (예시)
      - name: Build AsciiDoc to HTML
        run: |
          mkdir -p docs
          asciidoctor src/docs/asciidoc/index.adoc -o docs/index.html

      # 사용자 정보 설정
      - name: Set git user
        run: |
          git config --global user.email "rmfls4359@gmail.com"  # 본인의 이메일 주소로 수정
          git config --global user.name "kane park"  # 본인의 이름으로 수정
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DOSI-RAK/dosirak-be.git

     # gh-pages 브랜치가 존재하지 않으면, orphan 브랜치로 생성
      - name: Create gh-pages branch if not exists
        run: |
          if ! git show-ref --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages  # gh-pages 브랜치 생성
            git reset --hard                # 기존 파일 삭제
            git add docs/index.html         # HTML 파일만 추가
            git commit -m "Initial commit for GitHub Pages"
            git push origin gh-pages --force
          else
            git checkout gh-pages           # 기존 gh-pages 브랜치로 체크아웃
            git add docs/index.html         # HTML 파일만 추가
            git commit -m "Deploy to GitHub Pages"
            git push origin gh-pages --force
          fi

      # GitHub Pages에 푸시 (이미 `gh-pages` 브랜치가 설정되어 있어야 함)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs  # docs 폴더에 배포
